# ----------------------- pyMilne Inversion configuration --------------------------------
# # Data directory
# data_dir: "/mn/stornext/d18/lapalma/reduc/2020/2020-08-07/CRISP/cubes_nb/"
data_dir: '/mn/stornext/d18/lapalma/reduc/2021/2021-06-22/CRISP/cubes_nb/'
# data_dir: '/mn/stornext/d18/lapalma/reduc/2024/2024-05-21/CRISP/cubes_nb/'

# CRISP image file
# crisp_im: "nb_6173_2020-08-07T08:22:14_scans=0-56_stokes_corrected_im.fits"
crisp_im: 'nb_6173_2021-06-22T08:17:48_scans=0-162_stokes_corrected_im.fits'
# crisp_im: 'nb_6173_2024-05-21T10:19:04_10:19:04=0-52_stokes_corrected_im.fits'

# Save directory for saving temporary files and final outputs
# save_dir: "/mn/stornext/d9/data/avijeetp/1_Projects/61_QSEB_Topology/2020-08-07/"
save_dir: "/mn/stornext/d9/data/avijeetp/1_Projects/61_QSEB_Topology/2021-06-22/"
# save_dir: "/mn/stornext/d9/data/avijeetp/1_Projects/61_QSEB_Topology/2024-05-21/"

# Crop flag to crop the CRISP image and run inversion only for a smaller region of interest
crop: true
check_crop: false  # Interactively select the cropping region


# # Origin coordinates after cropping for the region of interest
xorg: 200  # Origin x-coordinate
yorg: 370  # Origin y-coordinate
# Size
xsize: 480  # Size along x-axis after cropping
ysize: 400  # Size along y-axis after cropping
# Rescale?
rescale: 2  # Scale down the cropped image by this factor (only for ambiguity resolution for now)

# Time range for the CRISP image in the format [start_time_index, end_time_index], [start_time_index, end_time_index, step_size], "first", "best", "full"
time_range: "best"

# Scale in arcsec/pixel
scale: 0.058 # 0.044

# North up flag to mark if the CRISP image is already oriented with north up
is_north_up: false

# Does the data need to be flipped left-right?
flip_lr: true

# Shape of the CRISP FOV in format ['shape', 'width', 'height] or ['shape', 'radius']
shape: ["square", 56, 56] # ["circle", 87] 

# HMI series for downloading the magnetogram and continuum images from JSOC
hmi_con_series: "hmi.Ic_45s"
hmi_mag_series: "hmi.M_45s"

# Email address used for JSOC download. You can optionally keep it empty string
email: ""

# Plot SST pointings? To plot SST pointings for the full observation over HMI Ic
plot_sst_pointings_flag: true

# Plot HMI Icon and Mag? To plot HMI Ic and Mag images with SST FOV overlaid for comparison
plot_hmi_ic_mag_flag: true

# Plot SST CRISP image to compare with HMI? To plot SST CRISP image for quick comparison with HMI Ic and Mag
plot_crisp_image_flag: true

# Show intermediate plots during inversion
verbose: true

# Set min-max values for the BLOS plot. Comment them out to use 1 and 99 percentile as default values
blos_min: -1000
blos_max: 1000

# Save the inversion results as fits
# ["Bstr", "Binc", "Bazi", "Vlos", "Vdop", "etal", "damp", "S0", "S1", "Blos", "Bhor", "Nan_mask"]
# ["Bstr_err", "Binc_err", "Bazi_err", "Vlos_err", "Vdop_err", "etal_err", "damp_err", "S0_err", "S1_err", "Blos_err", "Bhor_err", "Nan_mask"]

inversion_save_fits_list: []
inversion_save_errors_fits: false

# Save inversion results as LP cubes
inversion_save_lp_list: ["Blos", "Bhor", "Bazi", "Vlos"]
inversion_save_errors_lp: true

# Delete temporary files after inversion
delete_temp_files: true

# -------------------------- Ambiguity resolution config --------------------------
# Ambiguity resolution flag
run_ambiguity_resolution: true
# Path of the ambig executable obtained from the compiling the ME0-2.1.1 Fortran code
ambig_executable_path: '/mn/stornext/u3/avijeetp/codes/ambiguity_resolution/ME0-2.1.1/'

# Path of the ambig_par file which is the input file for the ambig executable
ambig_par: '/mn/stornext/u3/avijeetp/codes/pyMilne/ITA/ambig_par'

# Path of the fcube files obtained from the inversion, 
ambig_input_dir: '/mn/stornext/d9/data/avijeetp/1_Projects/33_SST/2022-06-24/northup/' # if absent, save_dir is used
ambig_save_dir: '/mn/stornext/d9/data/avijeetp/1_Projects/33_SST/2022-06-24/northup/' # if absent, save_dir is used
fbazi: 'Bazi_6173_2022-06-26_T073626_2022-06-26_T094322_t_0-189.fcube'  # azimuth file
fbhor: 'Bhor_6173_2022-06-26_T073626_2022-06-26_T094322_t_0-189.fcube'  # horizontal field file
fblos: 'Blos_6173_2022-06-26_T073626_2022-06-26_T094322_t_0-189.fcube'  # line of sight field file

# Rescale?
rescale: 1  # Scale down the cropped image by this factor (only for ambiguity resolution for now)
